rootdir/Android.bp: Move soong_namespace to first module position
Soong requires soong_namespace to be the first module in an
Android.bp file. This was previously placed after sh_binary and
prebuilt_etc modules, causing:

  error: a namespace must be the first module in the file

Move it to the top of the file, right after the SPDX header.